<?php if (isset($user)) {
    $id = $user->getId();
    $email = $user->getEmail();
    $password = $user->getPassword();
    $role = $user->getRole();
    $submit = 'Update User';
} else {
    $id = '';
    $email = '';
    $password = '';
    $role = '';
    $submit = 'Insert User';
}

?>

<form class="form-horizontal" id="insertForm" method="post" action="<?php echo $action; ?>">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="email" value="<?php echo $email; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
            <input type="text" name="password" value="<?php echo $password; ?>" class="form-control" id="inputPassword3" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Role</label>
        <div class="col-sm-10">
            <input type="text" name="role" value="<?php echo $role; ?>" class="form-control" id="inputRole3" placeholder="Role">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default"><?php echo $submit; ?></button>
        </div>
    </div>
</form>