<div>
    <?php echo $this->form()->openTag($form); ?>
        <?php if ($isUpdate): ?>
            <!-- Disabled fields will not be sent in $_POST so we have to create hidden fields -->
            <?php echo $this->formHidden($form->get('id')); ?>
            <?php echo $this->formHidden($form->get('date')); ?>
        <?php endif; ?>
        <table>
            <tr>
                <td colspan="2"><?php echo $this->formElementErrors($form->get('username')); ?></td>
            </tr>
            <tr>
                <td><strong>Username:</strong></td>
                <td><?php echo $this->formElement($form->get('username')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->formElementErrors($form->get('email')); ?></td>
            </tr>
            <tr>
                <td><strong>Email:</strong></td>
                <td><?php echo $this->formElement($form->get('email')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->formElementErrors($form->get('password')); ?></td>
            </tr>
            <tr>
                <td><strong>Password:</strong></td>
                <td><?php echo $this->formElement($form->get('password')) ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->formElementErrors($form->get('role')); ?></td>
            </tr>
            <tr>
                <td><strong>Role:</strong></td>
                <td><?php echo $this->formElement($form->get('role')) ?></td>
            </tr>
            <tr align="right">
                <td colspan="2"><?php echo $this->formElement($form->get('submit')) ?></td>
            </tr>
        </table>
    <?php echo $this->form()->closeTag(); ?>
</div>
