<div class="lead"><a href="<?php echo $this->url('user\users\view', ['id' => $this->identity()->id]) ?>">@<?php echo $this->identity()->username; ?></a> Welcome to your Control Panel</div>

<div>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
            <th>Date</th>
        </tr>
        <?php foreach($this->users as $user): ?>
            <tr>
                <td><a href="<?php echo $this->url('user\users\view', ['id' => $user->getId()]) ?>"><?php echo $this->escapeHtml($user->getId()); ?></a></td>
                <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                <td><?php echo $this->escapeHtml($user->getRole()); ?></td>
                <td><?php echo $this->escapeHtml($user->getDate()); ?></td>
                <?php if ($this->layout()->acl->isAllowed($this->identity()->role, 'user\users\update')): ?>
                <td><a class="btn btn-success" href="<?php echo $this->url('user\users\update', ['id' => $user->getId()]) ?>">Update</a></td>
                <?php endif; ?>
                <?php if ($this->layout()->acl->isAllowed($this->identity()->role, 'user\users\delete')): ?>
                <td><a class="btn btn-danger" href="<?php echo $this->url('user\users\delete', ['id' => $user->getId()]) ?>">Delete</a></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div>
    <p><a href="<?php echo $this->url('user\users\create') ?>">Create a new User</a> | <a href="<?php echo $this->url('user\login\logout') ?>">Logout</a> </p>
</div>