<div>
    <p><strong>Id:</strong> <?php echo $this->user->getId() ?></p>
    <p><strong>Username:</strong> <?php echo $this->user->getUsername() ?></p>
    <p><strong>Email:</strong> <?php echo $this->user->getEmail() ?></p>
    <p><strong>Password:</strong> <?php echo $this->user->getPassword() ?></p>
    <p><strong>Role:</strong> <?php echo $this->user->getRole() ?></p>
    <p><strong>Date:</strong> <?php echo $this->user->getDate() ?></p>
</div>