<div>
    <b>Id:</b> <?php echo $bookmark->getId(); ?><br>
    <b>Url:</b> <?php echo $bookmark->getUrl(); ?><br>
    <b>Title:</b> <?php echo $bookmark->getTitle(); ?><br>
    <b>Description:</b> <?php echo $bookmark->getDescription(); ?><br>
    <b>Date:</b> <?php echo $bookmark->getDate(); ?><br>
    <b>Votes:</b> <?php echo $bookmark->getVotes(); ?><br>
    <b>IdUser:</b> <?php echo $bookmark->getIdUser(); ?>
</div>