<h1>Users</h1>

<div>
    <table class="table table-bordered">
        <thead>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>Password</th>
            <th>Role</th>
            <th>Date</th>
        </thead>
        <?php foreach ($users as $user): ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->getId()); ?></td>
            <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($user->getPassword()); ?></td>
            <td><?php echo $this->escapeHtml($user->getRole()); ?></td>
            <td><?php echo $this->escapeHtml($user->getDate()); ?></td>
            <td><a class="btn btn-success" href="<?php echo $this->url('user\user\update', array('id' => $user->getId())); ?>">Update</a></td>
            <td><a class="btn btn-danger" href="<?php echo $this->url('user\user\delete', array('id' => $user->getId())); ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div>
    <a class="btn btn-success" href="<?php echo $this->url('user\user\add'); ?>">New user</a>
</div>