<h1>Users</h1>

<div>
    <table class="table table-bordered">
        <thead>
        <th>Username</th>
        <th>Date</th>
        </thead>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                <td><?php echo $this->escapeHtml($user->getDate()); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
